set_global_assignment -name SDC_FILE ../NeoGeo.sdc
set_global_assignment -name SYSTEMVERILOG_FILE ../NeoGeo_MiST.sv
set_global_assignment -name VERILOG_FILE ../../mist/data_io_neogeo.v
set_global_assignment -name QIP_FILE ../../mist/mist-modules/mist.qip
set_global_assignment -name QIP_FILE ../../rtl/neogeo.qip
set_global_assignment -name QIP_FILE ../DeMiSTify/controller/controller.qip
set_global_assignment -name VHDL_FILE ../demistify_config_pkg.vhd
set_global_assignment -name VHDL_FILE ../firmware/controller_rom1_byte.vhd
set_global_assignment -name VHDL_FILE ../firmware/controller_rom2_byte.vhd
set_global_assignment -name PRE_FLOW_SCRIPT_FILE quartus_sh:../../mist/build_id.tcl
